import { Ticket } from '../types';

export const SAMPLE_TICKETS: Ticket[] = [
  {
    id: '1700000001',
    userId: '3',
    campus: 'Maysan Campus',
    building: 'CEIT',
    room: 'Comlab 201 2nd Flr',
    unitId: 'CL 201-03',
    issueType: 'Hardware',
    issueSubtype: 'Monitor not working',
    issueDescription: 'The monitor is not displaying anything. The power light is on but the screen remains black.',
    images: [],
    status: 'in_progress',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedBy: '2',
    adminNotes: 'Will check the monitor cable and try replacing the monitor if needed.',
  },
  {
    id: '1700000002',
    userId: '3',
    campus: 'Maysan Campus',
    building: 'CEIT',
    room: 'Comlab 202 2nd Flr',
    unitId: 'CL 202-05',
    issueType: 'Software',
    issueSubtype: 'Application not working',
    issueDescription: 'Microsoft Word is crashing every time I try to open a document.',
    images: [],
    status: 'submitted',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '1700000003',
    userId: '3',
    campus: 'Annex Campus',
    building: 'CAS',
    room: 'CAS A 3rd Flr',
    unitId: 'CAS A-02',
    issueType: 'Network',
    issueSubtype: 'No internet connection',
    issueDescription: 'Cannot connect to the internet. WiFi shows connected but no internet access.',
    images: [],
    status: 'resolved',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedBy: '2',
    adminNotes: 'Router was reset and connection restored.',
    resolutionNote: 'Confirmed that internet connection is working properly. Issue resolved.',
    resolvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '1700000004',
    userId: '3',
    campus: 'Maysan Campus',
    building: 'CEIT',
    room: 'Comlab 203 2nd Flr',
    unitId: 'CL 203-01',
    issueType: 'Hardware',
    issueSubtype: 'Keyboard malfunction',
    issueDescription: 'Several keys on the keyboard are not working, including the spacebar and enter key.',
    images: [],
    status: 'pending_resolution',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    acceptedBy: '2',
    adminNotes: 'Keyboard has been replaced with a new one.',
  },
  {
    id: '1700000005',
    userId: '3',
    campus: 'Maysan Campus',
    building: 'COED',
    room: 'Edtech A 3rd Flr',
    unitId: 'ED A-04',
    issueType: 'Software',
    issueSubtype: 'Update required',
    issueDescription: 'The antivirus software is outdated and needs to be updated.',
    images: [],
    status: 'requested',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    acceptedBy: '2',
  },
];
